site_name: OpenVK Documentation
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: grey
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant

repo_url: https://github.com/openvk/docs
repo_name: openvk/docs

nav:
  - 'Main page': 'index.md'
  - Chandler:
    - 'chandler/about.md'
    - 'chandler/installing.md'
  - 'OpenVK Engine':
    - 'openvk_engine/about.md'
    - 'openvk_engine/afterinstall.md'
    - 'API':
      - 'Objects':
        - 'Audio Genres': 'openvk_engine/api/objects/audio_genres.md'
        - 'Audio': 'openvk_engine/api/objects/audio.md'
        - 'Playlist': 'openvk_engine/api/objects/playlist.md'
        - 'User': 'openvk_engine/api/objects/user.md'
        - 'Group': 'openvk_engine/api/objects/group.md'
      - 'Methods':
        - 'Account':
          - 'account.getProfileInfo': 'openvk_engine/api/methods/account/getProfileInfo.md'
          - 'account.getInfo': 'openvk_engine/api/methods/account/getInfo.md'
          - 'account.setOnline': 'openvk_engine/api/methods/account/setOnline.md'
          - 'account.getCounters': 'openvk_engine/api/methods/account/getCounters.md'
          - 'account.saveProfileInfo': 'openvk_engine/api/methods/account/saveProfileInfo.md'
          - 'account.getBalance': 'openvk_engine/api/methods/account/getBalance.md'
          - 'account.getOvkSettings': 'openvk_engine/api/methods/account/getOvkSettings.md'
          - 'account.sendVotes': 'openvk_engine/api/methods/account/sendVotes.md'
          - 'account.ban': 'openvk_engine/api/methods/account/ban.md'
          - 'account.unban': 'openvk_engine/api/methods/account/unban.md'
        - 'Audio':
          - 'audio.getById': 'openvk_engine/api/methods/audio/getById.md'
          - 'audio.isLagtrain': 'openvk_engine/api/methods/audio/isLagtrain.md'
          - 'audio.getPopular': 'openvk_engine/api/methods/audio/getPopular.md'
          - 'audio.search': 'openvk_engine/api/methods/audio/search.md'
          - 'audio.getCount': 'openvk_engine/api/methods/audio/getCount.md'
          - 'audio.get': 'openvk_engine/api/methods/audio/get.md'
          - 'audio.getLyrics': 'openvk_engine/api/methods/audio/getLyrics.md'
          - 'audio.beacon': 'openvk_engine/api/methods/audio/beacon.md'
          - 'audio.setBroadcast': 'openvk_engine/api/methods/audio/setBroadcast.md'
          - 'audio.getBroadcastList': 'openvk_engine/api/methods/audio/getBroadcastList.md'
          - 'audio.edit': 'openvk_engine/api/methods/audio/edit.md'
          - 'audio.add': 'openvk_engine/api/methods/audio/add.md'
          - 'audio.delete': 'openvk_engine/api/methods/audio/delete.md'
          - 'audio.getAlbums': 'openvk_engine/api/methods/audio/getAlbums.md'
          - 'audio.searchAlbums': 'openvk_engine/api/methods/audio/searchAlbums.md'
          - 'audio.addAlbum': 'openvk_engine/api/methods/audio/addAlbum.md'
          - 'audio.editAlbum': 'openvk_engine/api/methods/audio/editAlbum.md'
          - 'audio.deleteAlbum': 'openvk_engine/api/methods/audio/deleteAlbum.md'
          - 'audio.moveToAlbum': 'openvk_engine/api/methods/audio/moveToAlbum.md'
          - 'audio.removeFromAlbum': 'openvk_engine/api/methods/audio/removeFromAlbum.md'
          - 'audio.bookmarkAlbum': 'openvk_engine/api/methods/audio/bookmarkAlbum.md'
          - 'audio.unbookmarkAlbum': 'openvk_engine/api/methods/audio/unbookmarkAlbum.md'
        - 'Board':
          - 'board.addTopic': 'openvk_engine/api/methods/board/addTopic.md'
          - 'board.closeTopic': 'openvk_engine/api/methods/board/closeTopic.md'
          - 'board.createComment': 'openvk_engine/api/methods/board/createComment.md'
          - 'board.deleteComment': 'openvk_engine/api/methods/board/deleteComment.md'
          - 'board.deleteTopic': 'openvk_engine/api/methods/board/deleteTopic.md'
          - 'board.editTopic': 'openvk_engine/api/methods/board/editTopic.md'
          - 'board.fixTopic': 'openvk_engine/api/methods/board/fixTopic.md'
          - 'board.getComments': 'openvk_engine/api/methods/board/getComments.md'
          - 'board.getTopics': 'openvk_engine/api/methods/board/getTopics.md'
          - 'board.openTopic': 'openvk_engine/api/methods/board/openTopic.md'
          - 'board.unfixTopic': 'openvk_engine/api/methods/board/unfixTopic.md'
        - 'Friends':
          - 'friends.add': 'openvk_engine/api/methods/friends/add.md'
          - 'friends.areFriends': 'openvk_engine/api/methods/friends/areFriends.md'
          - 'friends.delete': 'openvk_engine/api/methods/friends/delete.md'
          - 'friends.get': 'openvk_engine/api/methods/friends/get.md'
          - 'friends.getRequests': 'openvk_engine/api/methods/friends/getRequests.md'
        - 'Gifts':
          - 'gifts.get': 'openvk_engine/api/methods/gifts/get.md'
          - 'gifts.getCategories': 'openvk_engine/api/methods/gifts/getCategories.md'
          - 'gifts.getGiftsInCategory': 'openvk_engine/api/methods/gifts/getGiftsInCategory.md'
          - 'gifts.send': 'openvk_engine/api/methods/gifts/send.md'
        - 'Groups':
          - 'groups.create': 'openvk_engine/api/methods/groups/create.md'
          - 'groups.edit': 'openvk_engine/api/methods/groups/edit.md'
          - 'groups.get': 'openvk_engine/api/methods/groups/get.md'
          - 'groups.getById': 'openvk_engine/api/methods/groups/getById.md'
          - 'groups.getMembers': 'openvk_engine/api/methods/groups/getMembers.md'
          - 'groups.getSettings': 'openvk_engine/api/methods/groups/getSettings.md'
          - 'groups.isMember': 'openvk_engine/api/methods/groups/isMember.md'
          - 'groups.join': 'openvk_engine/api/methods/groups/join.md'
          - 'groups.leave': 'openvk_engine/api/methods/groups/leave.md'
          - 'groups.search': 'openvk_engine/api/methods/groups/search.md'
        - 'Likes':
          - 'likes.add': 'openvk_engine/api/methods/likes/add.md'
          - 'likes.delete': 'openvk_engine/api/methods/likes/delete.md'
          - 'likes.getList': 'openvk_engine/api/methods/likes/getList.md'
          - 'likes.isLiked': 'openvk_engine/api/methods/likes/isLiked.md'
        - 'Messages':
          - 'messages.delete': 'openvk_engine/api/methods/messages/delete.md'
          - 'messages.edit': 'openvk_engine/api/methods/messages/edit.md'
          - 'messages.getById': 'openvk_engine/api/methods/messages/getById.md'
          - 'messages.getConversations': 'openvk_engine/api/methods/messages/getConversations.md'
          - 'messages.getConversationsById': 'openvk_engine/api/methods/messages/getConversationsById.md'
          - 'messages.getHistory': 'openvk_engine/api/methods/messages/getHistory.md'
          - 'messages.getLongPollHistory': 'openvk_engine/api/methods/messages/getLongPollHistory.md'
          - 'messages.getLongPollServer': 'openvk_engine/api/methods/messages/getLongPollServer.md'
          - 'messages.restore': 'openvk_engine/api/methods/messages/restore.md'
          - 'messages.send': 'openvk_engine/api/methods/messages/send.md'
        - 'Newsfeed':
          - 'newsfeed.addBan': 'openvk_engine/api/methods/newsfeed/addBan.md'
          - 'newsfeed.deleteBan': 'openvk_engine/api/methods/newsfeed/deleteBan.md'
          - 'newsfeed.get': 'openvk_engine/api/methods/newsfeed/get.md'
          - 'newsfeed.getBanned': 'openvk_engine/api/methods/newsfeed/getBanned.md'
          - 'newsfeed.getGlobal': 'openvk_engine/api/methods/newsfeed/getGlobal.md'
        - 'Notes':
          - 'notes.add': 'openvk_engine/api/methods/notes/add.md'
          - 'notes.createComment': 'openvk_engine/api/methods/notes/createComment.md'
          - 'notes.delete': 'openvk_engine/api/methods/notes/delete.md'
          - 'notes.edit': 'openvk_engine/api/methods/notes/edit.md'
          - 'notes.get': 'openvk_engine/api/methods/notes/get.md'
          - 'notes.getById': 'openvk_engine/api/methods/notes/getById.md'
          - 'notes.getComments': 'openvk_engine/api/methods/notes/getComments.md'
        - 'Notifications':
          - 'notifications.get': 'openvk_engine/api/methods/notifications/get.md'
          - 'notifications.markAsViewed': 'openvk_engine/api/methods/notifications/markAsViewed.md'
        - 'Ovk':
          - 'ovk.aboutInstance': 'openvk_engine/api/methods/ovk/aboutInstance.md'
          - 'ovk.chickenWings': 'openvk_engine/api/methods/ovk/chickenWings.md'
          - 'ovk.test': 'openvk_engine/api/methods/ovk/test.md'
          - 'ovk.version': 'openvk_engine/api/methods/ovk/version.md'
        - 'Pay':
          - 'pay.getIdByMarketingId': 'openvk_engine/api/methods/pay/getIdByMarketingId.md'
          - 'pay.verifyOrder': 'openvk_engine/api/methods/pay/verifyOrder.md'
        - 'Photos':
          - 'photos.createAlbum': 'openvk_engine/api/methods/photos/createAlbum.md'
          - 'photos.delete': 'openvk_engine/api/methods/photos/delete.md'
          - 'photos.deleteAlbum': 'openvk_engine/api/methods/photos/deleteAlbum.md'
          - 'photos.edit': 'openvk_engine/api/methods/photos/edit.md'
          - 'photos.editAlbum': 'openvk_engine/api/methods/photos/editAlbum.md'
          - 'photos.get': 'openvk_engine/api/methods/photos/get.md'
          - 'photos.getAlbums': 'openvk_engine/api/methods/photos/getAlbums.md'
          - 'photos.getAlbumsCount': 'openvk_engine/api/methods/photos/getAlbumsCount.md'
          - 'photos.getAll': 'openvk_engine/api/methods/photos/getAll.md'
          - 'photos.getById': 'openvk_engine/api/methods/photos/getById.md'
          - 'photos.getComments': 'openvk_engine/api/methods/photos/getComments.md'
          - 'photos.getOwnerPhotoUploadServer': 'openvk_engine/api/methods/photos/getOwnerPhotoUploadServer.md'
          - 'photos.getWallUploadServer': 'openvk_engine/api/methods/photos/getWallUploadServer.md'
          - 'photos.save': 'openvk_engine/api/methods/photos/save.md'
          - 'photos.saveOwnerPhoto': 'openvk_engine/api/methods/photos/saveOwnerPhoto.md'
          - 'photos.saveWallPhoto': 'openvk_engine/api/methods/photos/saveWallPhoto.md'
        - 'Polls':
          - 'polls.addVote': 'openvk_engine/api/methods/polls/addVote.md'
          - 'polls.create': 'openvk_engine/api/methods/polls/create.md'
          - 'polls.deleteVote': 'openvk_engine/api/methods/polls/deleteVote.md'
          - 'polls.getById': 'openvk_engine/api/methods/polls/getById.md'
          - 'polls.getVoters': 'openvk_engine/api/methods/polls/getVoters.md'
        - 'Reports':
          - 'reports.add': 'openvk_engine/api/methods/reports/add.md'
        - 'Status':
          - 'status.get': 'openvk_engine/api/methods/status/get.md'
          - 'status.get': 'openvk_engine/api/methods/status/set.md'
        - 'Users':
          - 'users.get': 'openvk_engine/api/methods/users/get.md'
          - 'users.getFollowers': 'openvk_engine/api/methods/users/getFollowers.md'
          - 'users.search': 'openvk_engine/api/methods/users/search.md'
        - 'Utils':
          - 'utils.getServerTime': 'openvk_engine/api/methods/utils/getServerTime.md'
          - 'utils.resolveScreenName': 'openvk_engine/api/methods/utils/resolveScreenName.md'
        - 'Video':
          - 'video.get': 'openvk_engine/api/methods/video/get.md'
          - 'video.search': 'openvk_engine/api/methods/video/search.md'
        - 'Wall':
          - 'wall.checkCopyrightLink': 'openvk_engine/api/methods/wall/checkCopyrightLink.md'
          - 'wall.createComment': 'openvk_engine/api/methods/wall/createComment.md'
          - 'wall.delete': 'openvk_engine/api/methods/wall/delete.md'
          - 'wall.deleteComment': 'openvk_engine/api/methods/wall/deleteComment.md'
          - 'wall.edit': 'openvk_engine/api/methods/wall/edit.md'
          - 'wall.editComment': 'openvk_engine/api/methods/wall/editComment.md'
          - 'wall.get': 'openvk_engine/api/methods/wall/get.md'
          - 'wall.getById': 'openvk_engine/api/methods/wall/getById.md'
          - 'wall.getComment': 'openvk_engine/api/methods/wall/getComment.md'
          - 'wall.getComments': 'openvk_engine/api/methods/wall/getComments.md'
          - 'wall.pin': 'openvk_engine/api/methods/wall/pin.md'
          - 'wall.post': 'openvk_engine/api/methods/wall/post.md'
          - 'wall.repost': 'openvk_engine/api/methods/wall/repost.md'
          - 'wall.unpin': 'openvk_engine/api/methods/wall/unpin.md'
      - 'openvk_engine/api/overview.md'
      - 'openvk_engine/api/authorization.md'
    - 'Tutorials':
      - 'openvk_engine/centos8_installation.md'
      - 'openvk_engine/ton_integration.md'
      - 'openvk_engine/themepack_creation.md'

copyright: Copyright &copy; 2021-2025 OpenVK Team and contributors

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openvk/openvk
      name: OpenVK on GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/openvk
      name: OpenVK on Telegram
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@openvk
      name: OpenVK on Mastodon
    - icon: fontawesome/solid/paper-plane
      link: mailto:openvk@tutanota.com
      name: Mail OpenVK

plugins:
  - git-revision-date

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
